//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica.Logica
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeShop
    {
        public int IdEmployee { get; set; }
        public int IdShop { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
